from typing import Annotated
from fastapi import APIRouter, HTTPException, Query
from sqlmodel import select
from models import Application, ApplicationCreate, ApplicationPublic, ApplicationUpdate
from database import SessionDep

router = APIRouter()  # replace @app with @router

# Step 10 : Create with ApplicationCreate and return an ApplicationPublic
# We receive in the request an ApplicationCreate data model, and from it, we create an Application table model
# This new table model Application will have the fields sent by the client, and will also have an id generated by the DB
# Then we return the same table model Application as is from the function. 
# But as we declare the response_model with ApplicationPublic data model, FastAPI will use ApplicationPublic to validate and serialize the data

@router.post("/applications", response_model = ApplicationPublic)
def create_application(application: ApplicationCreate, session: SessionDep):
    db_application = Application.model_validate(application)
    session.add(db_application)                             # Stage application to be saved
    session.commit()                                        # Save to DB
    session.refresh(db_application)                         # Refresh with DB generated values(e.g: id)
    return db_application

# Step 11: Read Applications with ApplicationPublic
# We will use response_model = list[ApplicationPublic] to ensure that the data is validated and serialized correctly
# Extension : Filer by status

@router.get("/applications", response_model = list[ApplicationPublic])
def read_applications(
    session: SessionDep,                                           # Injected DB session
    offset: int = 0,                                               # Skip N applications (e.g: offset = 5 skips first 5)
    limit: Annotated[int, Query(le = 100)] = 100,                  # Max applications to return, capped at 100
    status: str | None = None,                                     # Optional filter by status
    ):
    query = select(Application)                                    # SELECT * FROM Application
    if status:                                                     # Check if status is provided
        query = query.where(Application.status == status)          # Filter by status
    applications = session.exec(                                   # Executes the query
        query                                                      # Filter by status
        .offset(offset)                                            # Skip N rows
        .limit(limit)                                              # Take only N rows
        ).all()                                                    # Return all results as a list
    return applications

# Step 12: Read One Application with HeroPublic
# We can read a single application

@router.get("/applications/{id}", response_model = ApplicationPublic)
def read_application(id: int, session: SessionDep):
    application = session.get(Application, id)
    if not application:                                                           # Check if application do not exist
        raise HTTPException(status_code = 404, detail = "Application not found")  # Raise the following message
    return application                                                            # Return single application

# Step 13: Update an Application with ApplicationUpdate
# We can update an application. For this, we will use an HTTP PATCH operation
# And in the code, we get a dict with all data sent by the client, *only the data sent by the client*, excluding any values that would be there just for being the default values.
# To do it, we will use exclude_unset = True. This is the main trick
# Then we will use application_db.sqlmodel_update(application_data) to update the application_db with the data from application_data
@router.patch("/applications/{id}", response_model = ApplicationPublic)
def update_application(id: int, application: ApplicationUpdate, session: SessionDep):
    application_db = session.get(Application, id)
    if not application_db:                                                          # Check if application_db do not exist
        raise HTTPException(status_code = 404, detail = "Application not found")    # Raise the following message
    application_data = application.model_dump(exclude_unset = True)
    application_db.sqlmodel_update(application_data)
    session.add(application_db)
    session.commit()
    session.refresh(application_db)
    return application_db

# Step 14: Delete an application

@router.delete("/applications/{id}")
def delete_application(id: int, session: SessionDep):
    application = session.get(Application, id)
    if not application:                                                             # Check if application do not exist
        raise HTTPException(status_code = 404, detail = "Application not found")    # Raise the following message
    session.delete(application)                                                     # Delete (stage) application
    session.commit()                                                                # Save to DB
    return {"ok": True}
